[package]
name = "enbyt"
version = "0.1.0"
edition = "2024"
license = "MIT"

authors = ["Alex Podikoglou"]
description = "Library for Serializing/Deserializing NBT Data"
documentation = "https://docs.rs/enbyt"
readme = "README.md"
repository = "https://github.com/yumemc/enbyt"
keywords = ["minecraft", "data-format"]

[dependencies]
flate2 = "1.1.9"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2.0.20"
winnow = "1.0.4"

[dev-dependencies]
criterion = "0.8.2"
hegeltest = "0.29.3"

[[bench]]
name = "deserialization"
harness = false

[[bench]]
name = "serialization"
harness = false
