[package]
name = "enbyt"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.9"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2.0.20"
winnow = "1.0.4"

[dev-dependencies]
criterion = "0.8.2"
hegeltest = "0.29.3"

[[bench]]
name = "deserialize_compressed"
harness = false
